export const auth = {
  ACCOUNT: "Account",
  ACCOUNTS: "Accounts",
  ACCOUNTS_DESCRIPTION: "Switch between your currently signed in accounts.",
  ACCOUNTS_INSTRUCTIONS: "Sign in to an additional account.",
  ADD_ACCOUNT: "Add Account",
  ADD_PASSKEY: "Add Passkey",
  ALREADY_HAVE_AN_ACCOUNT: "Already have an account?",
  AVATAR: "Avatar",
  AVATAR_DESCRIPTION: "Click on the avatar to upload a custom one from your files.",
  AVATAR_INSTRUCTIONS: "An avatar is optional but strongly recommended.",
  BACKUP_CODE_REQUIRED: "Backup code is required",
  BACKUP_CODES: "Backup Codes",
  BACKUP_CODES_DESCRIPTION:
    "Save these backup codes in a secure place. You can use them to access your account if you lose your two-factor authentication method.",
  BACKUP_CODE_PLACEHOLDER: "Backup Code",
  BACKUP_CODE: "Backup Code",
  CANCEL: "Cancel",
  CHANGE_PASSWORD: "Change Password",
  CHANGE_PASSWORD_DESCRIPTION: "Enter your current password and a new password.",
  CHANGE_PASSWORD_INSTRUCTIONS: "Please use 8 characters at minimum.",
  CHANGE_PASSWORD_SUCCESS: "Your password has been changed.",
  CONFIRM_PASSWORD: "Confirm Password",
  CONFIRM_PASSWORD_PLACEHOLDER: "Confirm Password",
  CONFIRM_PASSWORD_REQUIRED: "Confirm password is required",
  CONTINUE_WITH_AUTHENTICATOR: "Continue with Authenticator",
  COPIED_TO_CLIPBOARD: "Copied to clipboard",
  COPY_TO_CLIPBOARD: "Copy to clipboard",
  COPY_ALL_CODES: "Copy all codes",
  CONTINUE: "Continue",
  CURRENT_PASSWORD: "Current Password",
  CURRENT_PASSWORD_PLACEHOLDER: "Current Password",
  CURRENT_SESSION: "Current Session",
  DELETE: "Delete",
  DELETE_AVATAR: "Delete Avatar",
  DELETE_ACCOUNT: "Delete Account",
  DELETE_ACCOUNT_DESCRIPTION:
    "Permanently remove your account and all of its contents. This action is not reversible, so please continue with caution.",
  DELETE_ACCOUNT_INSTRUCTIONS:
    "Please confirm the deletion of your account. This action is not reversible, so please continue with caution.",
  DELETE_ACCOUNT_VERIFY: "Please check your email to verify the deletion of your account.",
  DELETE_ACCOUNT_SUCCESS: "Your account has been deleted.",
  DISABLE_TWO_FACTOR: "Disable Two-Factor",
  DISABLED_CREDENTIALS_DESCRIPTION: "Choose a provider to login to your account",
  DONT_HAVE_AN_ACCOUNT: "Don't have an account?",
  DONE: "Done",
  EMAIL: "Email",
  EMAIL_DESCRIPTION: "Enter the email address you want to use to log in.",
  EMAIL_INSTRUCTIONS: "Please enter a valid email address.",
  EMAIL_IS_THE_SAME: "Email is the same",
  EMAIL_PLACEHOLDER: "m@example.com",
  EMAIL_REQUIRED: "Email address is required",
  EMAIL_VERIFY_CHANGE: "Please check your email to verify the change.",
  EMAIL_VERIFICATION: "Please check your email for the verification link.",
  ENABLE_TWO_FACTOR: "Enable Two-Factor",
  IS_INVALID: "is invalid",
  IS_REQUIRED: "is required",
  FIELD_IS_REQUIRED: "{field} is required",
  IS_THE_SAME: "is the same",
  FORGOT_AUTHENTICATOR: "Forgot authenticator?",
  FORGOT_PASSWORD: "Forgot Password",
  FORGOT_PASSWORD_ACTION: "Send reset link",
  FORGOT_PASSWORD_DESCRIPTION: "Enter your email to reset your password",
  FORGOT_PASSWORD_EMAIL: "Check your email for the password reset link.",
  FORGOT_PASSWORD_LINK: "Forgot your password?",
  LINK: "Link",
  MAGIC_LINK: "Magic Link",
  MAGIC_LINK_ACTION: "Send magic link",
  MAGIC_LINK_DESCRIPTION: "Enter your email to receive a magic link",
  MAGIC_LINK_EMAIL: "Check your email for the magic link",
  EMAIL_OTP: "Email Code",
  EMAIL_OTP_SEND_ACTION: "Send code",
  EMAIL_OTP_VERIFY_ACTION: "Verify code",
  EMAIL_OTP_DESCRIPTION: "Enter your email to receive a code",
  EMAIL_OTP_VERIFICATION_SENT: "Please check your email for the verification code.",
  NAME: "Name",
  NAME_DESCRIPTION: "Please enter your full name, or a display name.",
  NAME_INSTRUCTIONS: "Please use {maxLength} characters at maximum.",
  NAME_PLACEHOLDER: "Name",
  NEW_PASSWORD: "New Password",
  NEW_PASSWORD_PLACEHOLDER: "New Password",
  NEW_PASSWORD_REQUIRED: "New password is required",
  ONE_TIME_PASSWORD: "One-Time Password",
  OR_CONTINUE_WITH: "Or continue with",
  PASSKEY: "Passkey",
  PASSKEYS: "Passkeys",
  PASSKEYS_DESCRIPTION: "Manage your passkeys for secure access.",
  PASSKEYS_INSTRUCTIONS: "Securely access your account without a password.",
  PERSONAL_ACCOUNT: "Personal Account",
  PASSWORD: "Password",
  PASSWORD_PLACEHOLDER: "Password",
  PASSWORD_REQUIRED: "Password is required",
  PASSWORDS_DO_NOT_MATCH: "Passwords do not match",
  PROVIDERS: "Providers",
  PROVIDERS_DESCRIPTION: "Connect your account with a third-party service.",
  RECOVER_ACCOUNT: "Recover Account",
  RECOVER_ACCOUNT_ACTION: "Recover account",
  RECOVER_ACCOUNT_DESCRIPTION: "Please enter a backup code to access your account",
  REMEMBER_ME: "Remember me",
  RESEND_CODE: "Resend code",
  RESEND_VERIFICATION_EMAIL: "Resend Verification Email",
  RESET_PASSWORD: "Reset Password",
  RESET_PASSWORD_ACTION: "Save new password",
  RESET_PASSWORD_DESCRIPTION: "Enter your new password below",
  RESET_PASSWORD_SUCCESS: "Password reset successfully",
  REQUEST_FAILED: "Request failed",
  REVOKE: "Revoke",
  SIGN_IN: "Sign In",
  SIGN_IN_ACTION: "Login",
  SIGN_IN_DESCRIPTION: "Enter your email below to login to your account",
  SIGN_IN_USERNAME_DESCRIPTION: "Enter your username or email to login to your account",
  SIGN_IN_WITH: "Sign in with",
  SIGN_OUT: "Sign Out",
  SIGN_UP: "Sign Up",
  SIGN_UP_ACTION: "Create an account",
  SIGN_UP_DESCRIPTION: "Enter your information to create an account",
  SIGN_UP_EMAIL: "Check your email for the verification link.",
  SESSIONS: "Sessions",
  SESSIONS_DESCRIPTION: "Manage your active sessions and revoke access.",
  SET_PASSWORD: "Set Password",
  SET_PASSWORD_DESCRIPTION:
    "Click the button below to receive an email to set up a password for your account.",
  SETTINGS: "Settings",
  SAVE: "Save",
  SECURITY: "Security",
  SWITCH_ACCOUNT: "Switch Account",
  TRUST_DEVICE: "Trust this device",
  TWO_FACTOR: "Two-Factor",
  TWO_FACTOR_ACTION: "Verify code",
  TWO_FACTOR_DESCRIPTION: "Please enter your one-time password to continue",
  TWO_FACTOR_CARD_DESCRIPTION: "Add an extra layer of security to your account.",
  TWO_FACTOR_DISABLE_INSTRUCTIONS: "Please enter your password to disable 2FA.",
  TWO_FACTOR_ENABLE_INSTRUCTIONS: "Please enter your password to enable 2FA.",
  TWO_FACTOR_ENABLED: "Two-factor authentication has been enabled",
  TWO_FACTOR_DISABLED: "Two-Factor Authentication has been disabled",
  TWO_FACTOR_PROMPT: "Two-Factor Authentication",
  TWO_FACTOR_TOTP_LABEL: "Scan the QR Code with your Authenticator",
  SEND_VERIFICATION_CODE: "Send verification code",
  UNLINK: "Unlink",
  UPDATED_SUCCESSFULLY: "updated successfully",
  USERNAME: "Username",
  USERNAME_DESCRIPTION: "Enter the username you want to use to log in.",
  USERNAME_INSTRUCTIONS: "Please use 32 characters at maximum.",
  USERNAME_PLACEHOLDER: "Username",
  SIGN_IN_USERNAME_PLACEHOLDER: "Username or email",
  VERIFY_YOUR_EMAIL: "Verify Your Email",
  VERIFY_YOUR_EMAIL_DESCRIPTION:
    "Please verify your email address. Check your inbox for the verification email. If you haven't received the email, click the button below to resend.",
  GO_BACK: "Go back",
  SESSION_NOT_FRESH: "Your session is not fresh. Please sign in again.",
  UPLOAD_AVATAR: "Upload Avatar",
  LOGO: "Logo",
  LOGO_DESCRIPTION: "Click on the logo to upload a custom one from your files.",
  LOGO_INSTRUCTIONS: "A logo is optional but strongly recommended.",
  UPLOAD: "Upload",
  UPLOAD_LOGO: "Upload Logo",
  DELETE_LOGO: "Delete Logo",
  PRIVACY_POLICY: "Privacy Policy",
  TERMS_OF_SERVICE: "Terms of Service",
  PROTECTED_BY_RECAPTCHA: "This site is protected by reCAPTCHA.",
  BY_CONTINUING_YOU_AGREE: "By continuing, you agree to the",
  USER: "User",
};
