export const organization = {
  API_KEYS: "API Keys",
  API_KEYS_DESCRIPTION: "Manage your API keys for secure access.",
  API_KEYS_INSTRUCTIONS: "Generate API keys to access your account programmatically.",
  CREATE_API_KEY: "Create API Key",
  CREATE_API_KEY_DESCRIPTION:
    "Enter a unique name for your API key to differentiate it from other keys.",
  API_KEY_NAME_PLACEHOLDER: "New API Key",
  API_KEY_CREATED: "API Key Created",
  CREATE_API_KEY_SUCCESS:
    "Please copy your API key and store it in a safe place. For security reasons we cannot show it again.",
  NEVER_EXPIRES: "Never Expires",
  EXPIRES: "Expires",
  NO_EXPIRATION: "No Expiration",
  DELETE_API_KEY: "Delete API Key",
  DELETE_API_KEY_CONFIRM: "Are you sure you want to delete this API key?",
  API_KEY: "API Key",
  CREATE_ORGANIZATION: "Create Organization",
  ORGANIZATION: "Organization",
  ORGANIZATION_NAME: "Name",
  ORGANIZATION_NAME_PLACEHOLDER: "Acme Inc.",
  ORGANIZATION_NAME_DESCRIPTION: "This is your organization's visible name.",
  ORGANIZATION_NAME_INSTRUCTIONS: "Please use 32 characters at maximum.",
  ORGANIZATION_SLUG: "Slug URL",
  ORGANIZATION_SLUG_DESCRIPTION: "This is your organization's URL namespace.",
  ORGANIZATION_SLUG_INSTRUCTIONS: "Please use 48 characters at maximum.",
  ORGANIZATION_SLUG_PLACEHOLDER: "acme-inc",
  CREATE_ORGANIZATION_SUCCESS: "Organization created successfully",
  ORGANIZATIONS: "Organizations",
  ORGANIZATIONS_DESCRIPTION: "Manage your organizations and memberships.",
  ORGANIZATIONS_INSTRUCTIONS: "Create an organization to collaborate with other users.",
  LEAVE_ORGANIZATION: "Leave Organization",
  LEAVE_ORGANIZATION_CONFIRM: "Are you sure you want to leave this organization?",
  LEAVE_ORGANIZATION_SUCCESS: "You have successfully left the organization.",
  MANAGE_ORGANIZATION: "Manage Organization",
  REMOVE_MEMBER: "Remove Member",
  REMOVE_MEMBER_CONFIRM: "Are you sure you want to remove this member from the organization?",
  REMOVE_MEMBER_SUCCESS: "Member removed successfully",
  INVITE_MEMBER: "Invite Member",
  MEMBERS: "Members",
  MEMBERS_DESCRIPTION: "Add or remove members and manage their roles.",
  MEMBERS_INSTRUCTIONS: "Invite new members to your organization.",
  INVITE_MEMBER_DESCRIPTION: "Send an invitation to add a new member to your organization.",
  ROLE: "Role",
  SELECT_ROLE: "Select a role",
  ADMIN: "Admin",
  MEMBER: "Member",
  GUEST: "Guest",
  OWNER: "Owner",
  UPDATE_ROLE_DESCRIPTION: "Update the role for this member",
  UPDATE_ROLE: "Update Role",
  MEMBER_ROLE_UPDATED: "Member role updated successfully",
  SEND_INVITATION: "Send Invitation",
  SEND_INVITATION_SUCCESS: "Invitation sent successfully",
  PENDING_INVITATIONS: "Pending Invitations",
  PENDING_INVITATIONS_DESCRIPTION: "Manage pending invitations to your organization.",
  PENDING_USER_INVITATIONS_DESCRIPTION: "Invitations you've received from organizations.",
  CANCEL_INVITATION: "Cancel Invitation",
  INVITATION_CANCELLED: "Invitation cancelled successfully",
  ACCEPT_INVITATION: "Accept Invitation",
  ACCEPT_INVITATION_DESCRIPTION: "You have been invited to join an organization.",
  INVITATION_ACCEPTED: "Invitation accepted successfully",
  INVITATION_REJECTED: "Invitation rejected successfully",
  ACCEPT: "Accept",
  REJECT: "Reject",
  INVITATION_EXPIRED: "This invitation has expired",
  DELETE_ORGANIZATION: "Delete Organization",
  DELETE_ORGANIZATION_DESCRIPTION:
    "Permanently remove your organization and all of its contents. This action is not reversible — please continue with caution.",
  DELETE_ORGANIZATION_SUCCESS: "Organization deleted successfully",
  DELETE_ORGANIZATION_INSTRUCTIONS: "Enter the organization slug to continue:",
  SLUG_REQUIRED: "Organization slug is required",
  SLUG_DOES_NOT_MATCH: "The slug does not match",
};
