packages:
  - apps/*
  - packages/**
  - tooling/*

catalog:
  '@hookform/resolvers': ^5.2.2
  '@tanstack/react-query': ^5.90.2
  '@types/node': ^24.5.2
  date-fns: ^4.1.0
  drizzle-orm: ^0.44.5
  drizzle-zod: ^0.8.3
  hono: ^4.9.9
  lucide-react: ^0.544.0
  next: ^15.5.4
  next-intl: ^4.3.9
  react-hook-form: ^7.63.0
  type-fest: 5.0.1
  vite: ^7.1.7
  vitest: ^3.2.4
  zod: ^4.1.11
  zustand: ^5.0.2

catalogs:
  dev:
    '@biomejs/biome': ^2.2.4
    lefthook: ^1.13.5
    typescript: ^5.9.2
    ultracite: ^5.1.2
  react19:
    '@types/react': ^19.1.13
    '@types/react-dom': ^19.1.9
    react: ^19.1.1
    react-dom: ^19.1.1

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - lefthook
  - sharp

overrides:
  esbuild: ^0.25.10

publicHoistPattern:
  - '*prettier*'
