packages:
  - apps/*
  - packages/**
  - tooling/*

# minimumReleaseAge: 1440

catalog:
  hono: ^4.9.8
  lucide-react: ^0.544.0
  next: ^15.5.4
  next-intl: ^4.3.9
  type-fest: ^5.0.1
  vite: ^7.1.7
  '@types/node': ^24.5.2
  vitest: ^3.2.4
  zod: ^4.1.11

catalogs:
  react19:
    '@types/react': ^19.1.13
    '@types/react-dom': ^19.1.9
    react: ^19.1.1
    react-dom: ^19.1.1
  dev:
    '@biomejs/biome': ^2.2.4
    typescript: ^5.9.2
    lefthook: ^1.8.3
    ultracite: ^5.1.2

catalogMode: prefer

publicHoistPattern:
  - '*prettier*'

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - lefthook
  - sharp

overrides:
  esbuild: ^0.25.10
