export * from "@tabler/icons-react";
export {
  IconAlertCircle as AlertCircle,
  IconArrowLeft as ArrowLeft,
  IconBrandGithub as Github,
  IconBrandGoogle as Google,
  IconBrandX as X,
  IconCheck as Check,
  IconCloudUpload as UploadCloud,
  IconLoader2 as Loader2,
  IconQrcode as QrCode,
  IconSend as Send,
  IconTrash as Trash,
  IconUpload as Upload,
  IconUserX as UserX,
} from "@tabler/icons-react";

export {
  BuildingIcon,
  CheckIcon,
  ChevronsUpDown,
  CopyIcon,
  EllipsisIcon,
  FingerprintIcon,
  HomeIcon,
  KeyRoundIcon,
  LaptopIcon,
  LockIcon,
  LogInIcon,
  LogOutIcon,
  MailIcon,
  MenuIcon,
  PlusCircleIcon,
  RepeatIcon,
  SettingsIcon,
  SmartphoneIcon,
  UserCogIcon,
  UserRoundIcon,
  UserRoundPlus,
  UserX2Icon,
} from "lucide-react";
